### PR TITLE
Add habitat plan

### PR DESCRIPTION
**Pull request by elliott-davis**
Signed-off-by: Elliott Davis <elliott@excellent.io>

### CODE REVIEW

**Comment by zeenix** [comment]
@elliott-davis cool stuff but I think you meant to write "Add habitat-operator plan" instead in the titles. :) My first thought was "inception".

**Comment by LiliC** [comment]
Sorry, I am sort of missing the point of adding this, at first glance at least. :) Is it so that you can run the operator with habitat in your k8s cluster?

**Comment by asymmetric** [comment]
@elliott-davis I'm also not 100% sure about this, but it might just be that I'm not understanding your use-case.

Could you explain a bit the rationale?

**Comment by elliott-davis** [comment]
@lili exactly! It's so we can leverage the habitat exporters and the
habitat builder service to manage the habitat operator container. I'm happy
to add that to the commit message also.

**Comment by LiliC** [comment]
@elliott-davis One thing I do not understand is this part:

> It's so we can leverage the habitat exporters

What do you mean by that, how would the workflow look like? Thanks!

**Comment by elliott-davis** [comment]
hey @LiliC - So I was envisioning it working like so:
1. Connect the plan file to Builder
2. Enable the export to DockerHub exporter
3. On subsequent changes to the operator, the build service will build and export the new operator to DockerHub

I was hoping that this could replace the `make image` target and streamline the Docker export

**Comment by asymmetric** [comment]
@elliott-davis thanks! I see how this could be helpful, but OTOH i still think that the `image` target has a place, e.g. for local development.

Anyway, this LGTM.

**Pull request merged**
