### PR TITLE
vendor: update version of k8s.io repos to satisfy the dep gods

### PR DESCRIPTION
**Pull request by iaguis**
In the habitat-service-broker we want to vendor v0.1.13 of the
service-catalog which specifies kubernetes-1.9.1 as a constraint. This
conflicts with the habitat-operator.

There's no code change in vendored files.

### CODE REVIEW

**Comment by asymmetric** [comment]
Why not the latest minor, i.e. `kubernetes-1.9.6`?

**Comment by iaguis** [comment]
> EDIT: Get it, because you want to match the version in the SB. Wonder if a higher version would work, though.

I pushed a commit with `kubernetes-1.9.6` and @indradhanush tested it and it didn't work. I'll go back to the previous version.

**Comment by asymmetric** [comment]
Can we close this?

**Comment by iaguis** [comment]
Let's close this since it's not needed for now.

**Pull request closed without merging**
